language: objective-c
osx_image: xcode7.3

script:
  - xcodebuild -workspace SecuritytextOrgAPI.xcworkspace -scheme SecuritytextOrgAPI ONLY_ACTIVE_ARCH=NO
  - xcodebuild -workspace SecuritytextOrgAPI.xcworkspace -scheme SecuritytextOrgAPI -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s,OS=9.3' test